name: qenergy-backend
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - sqlalchemy==2.0.23
    - alembic==1.12.1
    - psycopg2-binary==2.9.9
    - pydantic==2.5.0
    - python-multipart==0.0.6
    - python-jose[cryptography]==3.3.0
    - passlib[bcrypt]==1.7.4
    - python-dotenv==1.0.0
    - pytest==8.3.3
    - pytest-cov==5.0.0
    - factory_boy==3.3.1
    - Faker==30.8.2
    - httpx==0.27.2
    - python-docx==1.1.2
    - azure-identity==1.15.0
    - openai==1.35.0
    - rapidfuzz==3.14.0
